# Generated by Django 2.0.2 on 2018-03-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='pub_date',
        ),
    ]
