version: '3'

services:
  db:
    image: postgres
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash init.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
